// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: protocol_gRPC.proto

package server2client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RPCAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // action ID equals to the function name
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCAction) Reset() {
	*x = RPCAction{}
	mi := &file_protocol_gRPC_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCAction) ProtoMessage() {}

func (x *RPCAction) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_gRPC_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCAction.ProtoReflect.Descriptor instead.
func (*RPCAction) Descriptor() ([]byte, []int) {
	return file_protocol_gRPC_proto_rawDescGZIP(), []int{0}
}

func (x *RPCAction) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RPCAction) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ClientEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEntity) Reset() {
	*x = ClientEntity{}
	mi := &file_protocol_gRPC_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEntity) ProtoMessage() {}

func (x *ClientEntity) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_gRPC_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEntity.ProtoReflect.Descriptor instead.
func (*ClientEntity) Descriptor() ([]byte, []int) {
	return file_protocol_gRPC_proto_rawDescGZIP(), []int{1}
}

func (x *ClientEntity) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ClientEntity) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type DataEntity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*DataEntity_User
	//	*DataEntity_Group
	Data          isDataEntity_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataEntity) Reset() {
	*x = DataEntity{}
	mi := &file_protocol_gRPC_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataEntity) ProtoMessage() {}

func (x *DataEntity) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_gRPC_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataEntity.ProtoReflect.Descriptor instead.
func (*DataEntity) Descriptor() ([]byte, []int) {
	return file_protocol_gRPC_proto_rawDescGZIP(), []int{2}
}

func (x *DataEntity) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DataEntity) GetData() isDataEntity_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataEntity) GetUser() *UserEntity {
	if x != nil {
		if x, ok := x.Data.(*DataEntity_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *DataEntity) GetGroup() *GroupEntity {
	if x != nil {
		if x, ok := x.Data.(*DataEntity_Group); ok {
			return x.Group
		}
	}
	return nil
}

type isDataEntity_Data interface {
	isDataEntity_Data()
}

type DataEntity_User struct {
	User *UserEntity `protobuf:"bytes,2,opt,name=user,proto3,oneof"`
}

type DataEntity_Group struct {
	Group *GroupEntity `protobuf:"bytes,3,opt,name=group,proto3,oneof"`
}

func (*DataEntity_User) isDataEntity_Data() {}

func (*DataEntity_Group) isDataEntity_Data() {}

type UserEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Identity      uint32                 `protobuf:"varint,4,opt,name=Identity,proto3" json:"Identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEntity) Reset() {
	*x = UserEntity{}
	mi := &file_protocol_gRPC_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEntity) ProtoMessage() {}

func (x *UserEntity) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_gRPC_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEntity.ProtoReflect.Descriptor instead.
func (*UserEntity) Descriptor() ([]byte, []int) {
	return file_protocol_gRPC_proto_rawDescGZIP(), []int{3}
}

func (x *UserEntity) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserEntity) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserEntity) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserEntity) GetIdentity() uint32 {
	if x != nil {
		return x.Identity
	}
	return 0
}

type GroupEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	GroupLeader   string                 `protobuf:"bytes,3,opt,name=group_leader,json=groupLeader,proto3" json:"group_leader,omitempty"`
	Desc          string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Auth          uint32                 `protobuf:"varint,5,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupEntity) Reset() {
	*x = GroupEntity{}
	mi := &file_protocol_gRPC_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupEntity) ProtoMessage() {}

func (x *GroupEntity) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_gRPC_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupEntity.ProtoReflect.Descriptor instead.
func (*GroupEntity) Descriptor() ([]byte, []int) {
	return file_protocol_gRPC_proto_rawDescGZIP(), []int{4}
}

func (x *GroupEntity) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupEntity) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GroupEntity) GetGroupLeader() string {
	if x != nil {
		return x.GroupLeader
	}
	return ""
}

func (x *GroupEntity) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *GroupEntity) GetAuth() uint32 {
	if x != nil {
		return x.Auth
	}
	return 0
}

var File_protocol_gRPC_proto protoreflect.FileDescriptor

const file_protocol_gRPC_proto_rawDesc = "" +
	"\n" +
	"\x13protocol_gRPC.proto\"=\n" +
	"\tRPCAction\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\"2\n" +
	"\fClientEntity\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"m\n" +
	"\n" +
	"DataEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\x04user\x18\x02 \x01(\v2\v.UserEntityH\x00R\x04user\x12$\n" +
	"\x05group\x18\x03 \x01(\v2\f.GroupEntityH\x00R\x05groupB\x06\n" +
	"\x04data\"p\n" +
	"\n" +
	"UserEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1a\n" +
	"\bIdentity\x18\x04 \x01(\rR\bIdentity\"~\n" +
	"\vGroupEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12!\n" +
	"\fgroup_leader\x18\x03 \x01(\tR\vgroupLeader\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x12\n" +
	"\x04auth\x18\x05 \x01(\rR\x04auth2f\n" +
	"\fDataProtocol\x12,\n" +
	"\x0fserverStreaming\x12\n" +
	".RPCAction\x1a\v.DataEntity0\x01\x12(\n" +
	"\rserverSending\x12\n" +
	".RPCAction\x1a\v.DataEntityB#Z!github.com/chin-172/server2clientb\x06proto3"

var (
	file_protocol_gRPC_proto_rawDescOnce sync.Once
	file_protocol_gRPC_proto_rawDescData []byte
)

func file_protocol_gRPC_proto_rawDescGZIP() []byte {
	file_protocol_gRPC_proto_rawDescOnce.Do(func() {
		file_protocol_gRPC_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_gRPC_proto_rawDesc), len(file_protocol_gRPC_proto_rawDesc)))
	})
	return file_protocol_gRPC_proto_rawDescData
}

var file_protocol_gRPC_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protocol_gRPC_proto_goTypes = []any{
	(*RPCAction)(nil),    // 0: RPCAction
	(*ClientEntity)(nil), // 1: ClientEntity
	(*DataEntity)(nil),   // 2: DataEntity
	(*UserEntity)(nil),   // 3: UserEntity
	(*GroupEntity)(nil),  // 4: GroupEntity
}
var file_protocol_gRPC_proto_depIdxs = []int32{
	3, // 0: DataEntity.user:type_name -> UserEntity
	4, // 1: DataEntity.group:type_name -> GroupEntity
	0, // 2: DataProtocol.serverStreaming:input_type -> RPCAction
	0, // 3: DataProtocol.serverSending:input_type -> RPCAction
	2, // 4: DataProtocol.serverStreaming:output_type -> DataEntity
	2, // 5: DataProtocol.serverSending:output_type -> DataEntity
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protocol_gRPC_proto_init() }
func file_protocol_gRPC_proto_init() {
	if File_protocol_gRPC_proto != nil {
		return
	}
	file_protocol_gRPC_proto_msgTypes[2].OneofWrappers = []any{
		(*DataEntity_User)(nil),
		(*DataEntity_Group)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_gRPC_proto_rawDesc), len(file_protocol_gRPC_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_gRPC_proto_goTypes,
		DependencyIndexes: file_protocol_gRPC_proto_depIdxs,
		MessageInfos:      file_protocol_gRPC_proto_msgTypes,
	}.Build()
	File_protocol_gRPC_proto = out.File
	file_protocol_gRPC_proto_goTypes = nil
	file_protocol_gRPC_proto_depIdxs = nil
}
