// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: protocol_gRPC.proto

package server2client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataProtocol_ServerStreaming_FullMethodName = "/DataProtocol/serverStreaming"
	DataProtocol_ServerSending_FullMethodName   = "/DataProtocol/serverSending"
)

// DataProtocolClient is the client API for DataProtocol service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Update
// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative protocol_gRPC.proto
type DataProtocolClient interface {
	ServerStreaming(ctx context.Context, in *RPCAction, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataEntity], error)
	ServerSending(ctx context.Context, in *RPCAction, opts ...grpc.CallOption) (*DataEntity, error)
}

type dataProtocolClient struct {
	cc grpc.ClientConnInterface
}

func NewDataProtocolClient(cc grpc.ClientConnInterface) DataProtocolClient {
	return &dataProtocolClient{cc}
}

func (c *dataProtocolClient) ServerStreaming(ctx context.Context, in *RPCAction, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataEntity], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataProtocol_ServiceDesc.Streams[0], DataProtocol_ServerStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RPCAction, DataEntity]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataProtocol_ServerStreamingClient = grpc.ServerStreamingClient[DataEntity]

func (c *dataProtocolClient) ServerSending(ctx context.Context, in *RPCAction, opts ...grpc.CallOption) (*DataEntity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataEntity)
	err := c.cc.Invoke(ctx, DataProtocol_ServerSending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataProtocolServer is the server API for DataProtocol service.
// All implementations must embed UnimplementedDataProtocolServer
// for forward compatibility.
//
// Update
// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative protocol_gRPC.proto
type DataProtocolServer interface {
	ServerStreaming(*RPCAction, grpc.ServerStreamingServer[DataEntity]) error
	ServerSending(context.Context, *RPCAction) (*DataEntity, error)
	mustEmbedUnimplementedDataProtocolServer()
}

// UnimplementedDataProtocolServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataProtocolServer struct{}

func (UnimplementedDataProtocolServer) ServerStreaming(*RPCAction, grpc.ServerStreamingServer[DataEntity]) error {
	return status.Errorf(codes.Unimplemented, "method ServerStreaming not implemented")
}
func (UnimplementedDataProtocolServer) ServerSending(context.Context, *RPCAction) (*DataEntity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerSending not implemented")
}
func (UnimplementedDataProtocolServer) mustEmbedUnimplementedDataProtocolServer() {}
func (UnimplementedDataProtocolServer) testEmbeddedByValue()                      {}

// UnsafeDataProtocolServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataProtocolServer will
// result in compilation errors.
type UnsafeDataProtocolServer interface {
	mustEmbedUnimplementedDataProtocolServer()
}

func RegisterDataProtocolServer(s grpc.ServiceRegistrar, srv DataProtocolServer) {
	// If the following call pancis, it indicates UnimplementedDataProtocolServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataProtocol_ServiceDesc, srv)
}

func _DataProtocol_ServerStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RPCAction)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataProtocolServer).ServerStreaming(m, &grpc.GenericServerStream[RPCAction, DataEntity]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataProtocol_ServerStreamingServer = grpc.ServerStreamingServer[DataEntity]

func _DataProtocol_ServerSending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProtocolServer).ServerSending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataProtocol_ServerSending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProtocolServer).ServerSending(ctx, req.(*RPCAction))
	}
	return interceptor(ctx, in, info, handler)
}

// DataProtocol_ServiceDesc is the grpc.ServiceDesc for DataProtocol service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataProtocol_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DataProtocol",
	HandlerType: (*DataProtocolServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "serverSending",
			Handler:    _DataProtocol_ServerSending_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "serverStreaming",
			Handler:       _DataProtocol_ServerStreaming_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protocol_gRPC.proto",
}
